services:
  backend:
    build: ./secretly_api
    container_name: secrets_backend
    environment:
      - MASTER_KEY=myrandomkeyfortesting
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs